[app]
name = "MyCoolApp"
version = "1.0.0"

[target]
dir = "ft3dre1000"

[train]
lr = 1e-3
batchSize = 128
decayStepSize = 100
decayGamma = 0.98
epoch = 2000

[settings]
rey = 600
num_pde = 16000
num_vibrate = 4800
num_bc = 7800
use_f64 = false
seed = 1
outer_iteration = 300               # Low Re 200 and high 300
layers = [2,16,32,64,32,16,3]

[settings-3d]
rey = 2000
num_pde = 160000
num_vibrate = 18000
num_bc = 80000
use_f64 = false
seed = 1
outer_iteration = 400               # Low Re 200 and high 300
layers = [3,32,64,64,128,128,128,64,64,32,4]
# layers = [3,32,64,64,64,64,64,64,64,32,4] #For final

[log]
on = true
dir = "logs"
legend_train = "Train MSE Loss with se"
legend_test = "Test MSE Loss with se"

